module.exports = {
    200 : 'Success',
    401 : 'Authentication Failed.',
    201 : 'Email verified successfully',
    1000 : 'Some unexpected error occurred.',
    1001 : 'Invalid request params.',
    1002 : 'Invalid user token.',
    1003 : 'Mobile number already exists.',
    1004 : 'User Name already exists.',
    1005 : 'Email already exists.',
    1006 : 'Please enter correct OTP. ',
    1007 : 'Email Already Verified',
    1008 : 'Password is incorrect',
    1009 : 'Mobile number already verified',
    1010 : 'Mobile number not exists',
    1011 : 'OTP expired!',
    1012 : 'We cannot find an account!',
    1013 : 'Invalid file type!',
    1014 : 'Account number already exists!',
    1015 : 'Document already submitted for approval!',
    1016 : 'Document already verified!',
    1017 : 'You need admin account to login',
    1018 : 'Entered password is incorrect',
    1019 : 'Your account is not active',
    1020 : 'Invalid module Id',
    1021: 'Alternate Mobile number already exists with another user.',
    1022: "User name already exists",
    1023: "User name is already updated",
    1024: "User mobile is not verified",
    1025: "You are blocked by admin.",
    1027: "You already own more than %s coins.",
    1028: "You already own more coins than allowed reload limit.",
    1029: "token not exist.",
    1030 : 'Request for OTP first',
    1031 : 'You can fetch release unit for last 3 month only.',
    1032 : 'Dispute has already been  raised',
    1033 : 'Dispute raised TTL has expired',     
    1034 : 'Sorry! Access Denied.', 
    1036 : 'Multiple failed login attempts. Please try after ' ,
    1037 : 'Please try after some time' ,
    1038 : 'Recover Password attempts have exhausted. Please try after ',   
    1039 : ' attempts remaining ',   
    1040 : "You're existing cash app user,can't log in here.",   
    1041 : "You're existing cash app user,can't reset here.",   
    1042 : "Please enter correct email/mobile no.",   
    1043 : "Limit reached for max user registration from your device.",
    1045 : 'Limit reached for max resend attempt.' ,
    1046 : 'Something went wrong',
    1044 : 'OTP attempt limit has reached. Please try after ' ,
    1046 : 'Something went wrong',
    1047 : 'OTP sent successfully',
    1048 : 'Email not Verified! Please verify your email.',
    1049 : 'Device not found',
    1050 : 'First name & Last name length should be between 3 to 20',
    1051 : 'Following id should not be empty',
    1052 : 'Unfollow ids should not be empty',
    1053 : 'User name is reserve. Please try another once.',
    1054 : 'Your email is already verified',
    1055 : "You can't login using email",
    1056 : "Invalid Country Code",
    1057 : "Login Send-otp attempts have exhausted. Please try after",
    1058 : "Login Password attempts have exhausted. Please try after",
    1059 : "Recovery Send-otp attempts have exhausted. Please try after",
    1060 : 'Recover Password attempts have exhausted. Please try after',
    1061 : 'Sms not send',
    1062 : "this keyword is already exist",
    1063 : "package not exists",
    1064 : "Bio shouldn’t be empty",
    1065 : "Bio must be greater than 150 character",
    1066 : "You have entered wrong client name",
    1067 : "You have entered wrong location",
    1068 : "We have received your request, Your profile is under review",
    1069 : "Your Score is Low, You are not able to create keyword",
    1070 : "Daily vote limit reached",
    1071 : "INVALID URL ENTER",
    1072 : "You have a entered wrong tags",
    1073 : "Bio must be less than 1000 character",
    1074 : "Tags are missing",
    1075 : "Bio should be between 155 to 1000 character",
    1076 : "Profile PIC is missing",
    1077 : "Your premium profile request is under review.",
    1078 : "Invalid Language selected",
    1079 : "There is no any user requested by this id",
    1080 : "You have enter wrong age group",
    1081 : "User not exist!",
    1082 : "You have already voted for ",
    1083 : "UUID is mandatory",
    1084 : "Max Vote count exceeded",
    1085 : "Max count Impression and Vote exceeded",
    1086 : "Max Impression count exceeded",
    1087 : "Slug is required!",
    1088 : "Slug is not exist!",
    1089 : "Primary language can't be empty!",
    1090 : "Secondary language can't be empty!",
    1091 : "Tags can't be empty!",
    1092 : "Twitter url is not empty!",
    1093 : "Instagram url is not empty!",
    1094 : "There is no any user requested by this id",
    1095 : 'Invalid social media url!',
    1096 : 'Invalid registration number!',
    1097 : 'Invalid registration year!',
    1098 : 'Invalid verification url!',
    1099 : 'Email not verified!',
    2000 : 'Invalid url1! ',
    2001 : 'Invalid url2! ',
    2002 : 'Invalid url3! ',
    2003 : 'Invalid is 500k followers! ',
    2004 : 'Invalid top search! ',
    2005 : 'Invalid up for vote! ',
    2006 : 'You are not eligible for vote',
    2007 : 'Invalid Keyword',
    2008 : 'Invalid Category',
    2009 : 'Invalid Package Type',
    2010 : 'Invalid Report Type',
    2011 : 'Invalid keyword Length',
    2012 : 'You are already Premium',
    2013 : 'You are already Professional',
    2014 : 'You are already verfired with other email',
    2015 : 'You email is not valid',
    2016 : `You're already on our waitlist`,
    2017 : `Please enter a valid Job Name you're looking for`,
    2018 : 'Invalid department name',
    2019 : 'Invalid job type',
    2020 : 'Invalid Referrer code, please check and try again',
    2021 : 'Max IP request limit reached',
    2022 : 'Verification email Already sent, Please check in your email'
};